AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  FollowerCount - Instagram Non-Follower Checker
  A serverless application to identify Instagram users who don't follow you back

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: provided.al2023
    Architectures:
      - arm64
    Environment:
      Variables:
        LOG_LEVEL: ERROR # Minimize logging for privacy

  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Requested-With'"
      AllowOrigin: !Sub "'${FrontendDomain}'"
      MaxAge: "'86400'"

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage

  FrontendDomain:
    Type: String
    Default: "*"
    Description: Frontend domain for CORS (e.g., https://your-app.com)

Resources:
  # API Gateway
  FollowerCountApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Description: FollowerCount API
      EndpointConfiguration:
        Type: REGIONAL
      BinaryMediaTypes:
        - "application/zip"
        - "application/x-zip-compressed"
        - "application/octet-stream"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 50
          ThrottlingRateLimit: 100

  # Lambda Function
  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub follower-count-analyze-${Stage}
      Description: Analyzes Instagram data to find non-followers
      CodeUri: backend/
      Handler: bootstrap
      MemorySize: 1024 # 1GB for processing large ZIP files
      Timeout: 60
      ReservedConcurrentExecutions: 50 # Limit concurrent executions
      Events:
        AnalyzePost:
          Type: Api
          Properties:
            RestApiId: !Ref FollowerCountApi
            Path: /api/analyze
            Method: POST
        AnalyzeOptions:
          Type: Api
          Properties:
            RestApiId: !Ref FollowerCountApi
            Path: /api/analyze
            Method: OPTIONS
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Deny
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
              Condition:
                StringEquals:
                  "logs:messageContent": "*username*"

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub follower-count-frontend-${Stage}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3600

  # S3 Bucket Policy
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # CloudFront Distribution (Optional but recommended)
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: ApiOrigin
            DomainName: !Sub "${FollowerCountApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "/${Stage}"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: "/api/*"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            ForwardedValues:
              QueryString: true
              Headers:
                - Content-Type
                - X-Requested-With
              Cookies:
                Forward: none
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${FollowerCountApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/api/analyze"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  FrontendBucketName:
    Description: S3 bucket for frontend hosting
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AWS::StackName}-FrontendBucket"

  FrontendWebsiteUrl:
    Description: S3 Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-FrontendWebsiteUrl"

  CloudFrontDistributionUrl:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${FrontendDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontUrl"

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref FrontendDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDistributionId"
